export const Roles = Object.freeze({
   ADMIN: "admin",
   INSTITUTION: "institution"
});

export const Permissions = Object.freeze({
   INSTITUTIONS: "INSTITUTIONS",
   COURSES: "COURSES",
   COURSES_USERS: "COURSES-USERS",
   COURSES_ASSESSMENTS: "COURSES-ASSESSMENTS",
   COURSES_OBJECTIVES: "COURSES-OBJECTIVES",
   COURSES_EDIT: "COURSES-EDIT",
   COURSES_DELETE: "COURSES-DELETE",
   ASSESSMENT: "ASSESSMENT",
   USERS: "USERS",
   USERS_APPROVE: "USERS-APPROVE",
   USERS_REVOKE: "USERS-REVOKE",
   USERS_EDIT: "USERS-EDIT",
   USERS_DELETE: "USERS-DELETE",
   REQUEST: "REQUEST",
   VERIFICATION: "VERIFICATION",
   MANAGEMENT: "MANAGEMENT",
   PROFILE: "PROFILE"
});
